// COMPREHENSIVE BLOOD VESSELS DATABASE

export const ALL_BLOOD_VESSELS = [
  // ==================== MAJOR ARTERIES ====================
  {
    name: 'Aorta',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Largest artery in the body, originating from the left ventricle, approximately 30 cm long.',
    function: 'Main conduit for oxygenated blood to the entire body. Divides into ascending, arch, and descending portions.',
    importance: 'Aortic aneurysm is life-threatening. Exercise improves aortic health.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 1.12, z: 0.04 },
    exercises: [
      { name: 'Aerobic Exercise', rank: 1, description: 'Maintains arterial health.' },
    ]
  },
  {
    name: 'Ascending Aorta',
    type: 'vein',
    category: 'cardiovascular',
    description: 'First portion of the aorta, rising from the left ventricle to the aortic arch.',
    function: 'Gives rise to coronary arteries supplying the heart muscle.',
    importance: 'Ascending aortic aneurysms may require urgent surgery.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.01, y: 1.16, z: 0.06 },
    exercises: []
  },
  {
    name: 'Aortic Arch',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Curved portion of the aorta giving rise to the great vessels to the head and arms.',
    function: 'Branches into brachiocephalic trunk, left common carotid, and left subclavian arteries.',
    importance: 'Contains baroreceptors for blood pressure regulation.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 1.2, z: 0.04 },
    exercises: []
  },
  {
    name: 'Descending Thoracic Aorta',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Portion of the aorta descending through the thorax.',
    function: 'Supplies the chest wall, esophagus, and bronchi.',
    importance: 'Thoracic aortic aneurysms can cause back pain.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 1.08, z: -0.04 },
    exercises: []
  },
  {
    name: 'Abdominal Aorta',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Portion of the aorta below the diaphragm, bifurcating into common iliac arteries at L4.',
    function: 'Supplies abdominal organs and lower body through multiple branches.',
    importance: 'Abdominal aortic aneurysm (AAA) screening recommended for elderly men.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 0.88, z: -0.02 },
    exercises: []
  },
  {
    name: 'Coronary Arteries',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Right and left coronary arteries arising from the aortic sinuses, supplying the heart.',
    function: 'Supply oxygenated blood to the heart muscle.',
    importance: 'Blockage causes heart attack. Exercise improves coronary health.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.03, y: 1.14, z: 0.1 },
    exercises: [
      { name: 'Cardiovascular Exercise', rank: 1, description: 'Reduces coronary artery disease risk.' },
    ]
  },
  {
    name: 'Brachiocephalic Trunk',
    type: 'vein',
    category: 'cardiovascular',
    description: 'First branch of the aortic arch, dividing into right common carotid and right subclavian.',
    function: 'Supplies blood to the right arm and right side of head/neck.',
    importance: 'Short but important vessel connecting aorta to right upper body.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.04, y: 1.25, z: 0.04 },
    exercises: []
  },
  {
    name: 'Common Carotid Artery (Right)',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Major artery on the right side of the neck, from brachiocephalic trunk.',
    function: 'Supplies blood to the head and brain, bifurcates into internal and external carotid.',
    importance: 'Carotid stenosis major cause of stroke. Pulse palpable in neck.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.05, y: 1.42, z: 0.04 },
    exercises: []
  },
  {
    name: 'Common Carotid Artery (Left)',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Major artery on the left side of the neck, directly from aortic arch.',
    function: 'Supplies blood to the head and brain, bifurcates into internal and external carotid.',
    importance: 'Contains carotid body (chemoreceptors) and carotid sinus (baroreceptors).',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.05, y: 1.42, z: 0.04 },
    exercises: []
  },
  {
    name: 'Internal Carotid Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Branch of common carotid entering the skull to supply the brain.',
    function: 'Major blood supply to the brain, forming part of the Circle of Willis.',
    importance: 'Stenosis or dissection causes stroke. Supplies 80% of cerebral blood.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.04, y: 1.52, z: 0.02 },
    exercises: []
  },
  {
    name: 'External Carotid Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Branch of common carotid supplying the face, scalp, and neck structures.',
    function: 'Supplies blood to the face, scalp, thyroid, and pharynx.',
    importance: 'Multiple branches to facial structures. Facial artery pulse at jaw.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.05, y: 1.5, z: 0.05 },
    exercises: []
  },
  {
    name: 'Vertebral Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Branch of subclavian artery ascending through cervical transverse foramina.',
    function: 'Supplies posterior brain through basilar artery.',
    importance: 'Dissection can cause stroke. Vulnerable during neck manipulation.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.03, y: 1.48, z: -0.04 },
    exercises: []
  },
  {
    name: 'Subclavian Artery (Right)',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Branch of brachiocephalic trunk supplying the right arm.',
    function: 'Supplies the right upper limb, becoming the axillary artery.',
    importance: 'Thoracic outlet syndrome can compress this artery.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.1, y: 1.32, z: 0.02 },
    exercises: []
  },
  {
    name: 'Subclavian Artery (Left)',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Direct branch of aortic arch supplying the left arm.',
    function: 'Supplies the left upper limb, becoming the axillary artery.',
    importance: 'Left arises directly from aortic arch, not brachiocephalic.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.1, y: 1.32, z: 0.02 },
    exercises: []
  },
  {
    name: 'Axillary Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Continuation of subclavian artery in the axilla.',
    function: 'Supplies the axilla and proximal arm, becoming the brachial artery.',
    importance: 'Can be damaged in shoulder dislocations.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.18, y: 1.28, z: 0.02 },
    exercises: []
  },
  {
    name: 'Brachial Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Main artery of the arm, from axillary artery to elbow.',
    function: 'Supplies the arm, commonly used for blood pressure measurement.',
    importance: 'BP measured here with stethoscope. Divides into radial and ulnar.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.24, y: 1.1, z: 0.04 },
    exercises: []
  },
  {
    name: 'Radial Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Lateral forearm artery, continuation of brachial artery.',
    function: 'Supplies lateral forearm and hand, pulse taken at wrist.',
    importance: 'Most common site for pulse check. Used for arterial blood gas.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.3, y: 0.85, z: 0.03 },
    exercises: []
  },
  {
    name: 'Ulnar Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Medial forearm artery from brachial artery.',
    function: 'Supplies medial forearm and hand.',
    importance: 'Forms the superficial palmar arch in the hand.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.3, y: 0.85, z: 0 },
    exercises: []
  },
  {
    name: 'Celiac Trunk',
    type: 'vein',
    category: 'cardiovascular',
    description: 'First major abdominal branch of aorta, at T12 level.',
    function: 'Supplies foregut organs: stomach, liver, spleen, and proximal duodenum.',
    importance: 'Three branches: left gastric, splenic, common hepatic.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 1.0, z: 0.02 },
    exercises: []
  },
  {
    name: 'Superior Mesenteric Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Second major abdominal branch of aorta, at L1 level.',
    function: 'Supplies midgut: small intestine, cecum, ascending and transverse colon.',
    importance: 'Occlusion causes mesenteric ischemia, a surgical emergency.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 0.95, z: 0.02 },
    exercises: []
  },
  {
    name: 'Inferior Mesenteric Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Third major abdominal branch of aorta, at L3 level.',
    function: 'Supplies hindgut: descending colon, sigmoid colon, rectum.',
    importance: 'Watershed area at splenic flexure prone to ischemia.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 0.85, z: 0.02 },
    exercises: []
  },
  {
    name: 'Renal Artery (Right)',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Branch of abdominal aorta to the right kidney.',
    function: 'Supplies blood to the right kidney for filtration.',
    importance: 'Renal artery stenosis causes renovascular hypertension.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.06, y: 0.92, z: -0.02 },
    exercises: []
  },
  {
    name: 'Renal Artery (Left)',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Branch of abdominal aorta to the left kidney.',
    function: 'Supplies blood to the left kidney for filtration.',
    importance: '25% of cardiac output goes to kidneys via renal arteries.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.06, y: 0.92, z: -0.02 },
    exercises: []
  },
  {
    name: 'Common Iliac Artery (Right)',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Terminal branch of abdominal aorta at L4 bifurcation.',
    function: 'Supplies pelvis and lower limb, divides into internal and external iliac.',
    importance: 'Aneurysms can occur here.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.06, y: 0.78, z: 0.02 },
    exercises: []
  },
  {
    name: 'Common Iliac Artery (Left)',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Terminal branch of abdominal aorta at L4 bifurcation.',
    function: 'Supplies pelvis and lower limb, divides into internal and external iliac.',
    importance: 'Aortic bifurcation is a surgical landmark.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.06, y: 0.78, z: 0.02 },
    exercises: []
  },
  {
    name: 'External Iliac Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Continuation of common iliac, becoming femoral artery under inguinal ligament.',
    function: 'Main blood supply to the lower limb.',
    importance: 'Passes under inguinal ligament to become femoral artery.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.08, y: 0.74, z: 0.04 },
    exercises: []
  },
  {
    name: 'Internal Iliac Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Branch of common iliac supplying pelvic organs and gluteal region.',
    function: 'Supplies pelvic organs, gluteal muscles, and perineum.',
    importance: 'Can be ligated to control pelvic hemorrhage.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.06, y: 0.74, z: -0.02 },
    exercises: []
  },
  {
    name: 'Femoral Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Main artery of the thigh, continuation of external iliac.',
    function: 'Supplies the thigh, pulse palpable in femoral triangle.',
    importance: 'Common site for arterial access (catheterization). Aneurysm possible.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.1, y: 0.6, z: 0.06 },
    exercises: []
  },
  {
    name: 'Popliteal Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Continuation of femoral artery behind the knee.',
    function: 'Supplies the knee and proximal leg, divides into tibial arteries.',
    importance: 'Popliteal aneurysms can cause leg ischemia.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.1, y: 0.4, z: -0.04 },
    exercises: []
  },
  {
    name: 'Anterior Tibial Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Branch of popliteal artery in the anterior leg compartment.',
    function: 'Supplies the anterior leg, becomes dorsalis pedis at ankle.',
    importance: 'Dorsalis pedis pulse checked on top of foot.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.1, y: 0.25, z: 0.04 },
    exercises: []
  },
  {
    name: 'Posterior Tibial Artery',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Branch of popliteal artery in the posterior leg compartment.',
    function: 'Supplies the posterior leg and sole of foot.',
    importance: 'Posterior tibial pulse checked behind medial malleolus.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.08, y: 0.2, z: -0.02 },
    exercises: []
  },

  // ==================== MAJOR VEINS ====================
  {
    name: 'Superior Vena Cava',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Large vein draining the upper body into the right atrium.',
    function: 'Returns deoxygenated blood from head, neck, arms, and upper thorax to the heart.',
    importance: 'SVC syndrome from compression causes facial/arm swelling.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.02, y: 1.22, z: 0.04 },
    exercises: []
  },
  {
    name: 'Inferior Vena Cava',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Largest vein in the body, draining the lower body into the right atrium.',
    function: 'Returns deoxygenated blood from legs, pelvis, and abdomen to the heart.',
    importance: 'IVC filters placed to prevent pulmonary embolism.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.02, y: 0.95, z: 0.02 },
    exercises: []
  },
  {
    name: 'Pulmonary Veins',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Four veins (two from each lung) carrying oxygenated blood to the left atrium.',
    function: 'Return oxygenated blood from the lungs to the heart.',
    importance: 'Only veins carrying oxygenated blood. Atrial fibrillation often originates here.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.04, y: 1.16, z: 0.02 },
    exercises: []
  },
  {
    name: 'Pulmonary Arteries',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Arteries from right ventricle carrying deoxygenated blood to the lungs.',
    function: 'Transport deoxygenated blood to the lungs for oxygenation.',
    importance: 'Pulmonary embolism blocks these arteries, can be fatal.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 1.18, z: 0.06 },
    exercises: []
  },
  {
    name: 'Internal Jugular Vein (Right)',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Major vein draining the brain, face, and neck.',
    function: 'Primary venous drainage of the brain and deep face.',
    importance: 'Common site for central venous catheter placement.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.06, y: 1.42, z: 0.02 },
    exercises: []
  },
  {
    name: 'Internal Jugular Vein (Left)',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Major vein draining the brain, face, and neck.',
    function: 'Primary venous drainage of the brain and deep face.',
    importance: 'JVD (jugular vein distension) indicates heart failure.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.06, y: 1.42, z: 0.02 },
    exercises: []
  },
  {
    name: 'External Jugular Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Superficial vein draining the scalp and face, visible in the neck.',
    function: 'Drains the superficial face and scalp.',
    importance: 'Visible distension indicates elevated central venous pressure.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.07, y: 1.44, z: 0.03 },
    exercises: []
  },
  {
    name: 'Subclavian Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Major vein draining the arm, continuation of axillary vein.',
    function: 'Returns blood from the arm to the brachiocephalic vein.',
    importance: 'Common site for central line placement.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.1, y: 1.34, z: 0.02 },
    exercises: []
  },
  {
    name: 'Brachiocephalic Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Formed by junction of internal jugular and subclavian veins.',
    function: 'Drains the head, neck, and arm into the superior vena cava.',
    importance: 'Left brachiocephalic crosses midline behind the manubrium.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.04, y: 1.3, z: 0.04 },
    exercises: []
  },
  {
    name: 'Cephalic Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Superficial vein on the lateral arm, from hand to deltopectoral groove.',
    function: 'Drains the lateral hand and arm.',
    importance: 'Common site for IV cannulation. Used for pacemaker leads.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.26, y: 1.15, z: 0.06 },
    exercises: []
  },
  {
    name: 'Basilic Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Superficial vein on the medial arm, becoming axillary vein.',
    function: 'Drains the medial hand and arm.',
    importance: 'Used for PICC line placement.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.24, y: 1.1, z: 0.02 },
    exercises: []
  },
  {
    name: 'Median Cubital Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Superficial vein connecting cephalic and basilic veins at the elbow.',
    function: 'Connection between superficial arm veins.',
    importance: 'Most common site for venipuncture (blood draws).',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.26, y: 1.0, z: 0.04 },
    exercises: []
  },
  {
    name: 'Hepatic Veins',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Three veins draining the liver directly into the IVC.',
    function: 'Drain the liver of filtered blood.',
    importance: 'Budd-Chiari syndrome involves hepatic vein obstruction.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.08, y: 1.02, z: 0.02 },
    exercises: []
  },
  {
    name: 'Portal Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Large vein carrying nutrient-rich blood from GI tract to the liver.',
    function: 'Brings absorbed nutrients from the gut to the liver for processing.',
    importance: 'Portal hypertension causes varices and ascites in liver disease.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.04, y: 0.96, z: 0.04 },
    exercises: []
  },
  {
    name: 'Splenic Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Vein draining the spleen, joining with SMV to form portal vein.',
    function: 'Drains the spleen and part of the pancreas.',
    importance: 'Splenic vein thrombosis can cause gastric varices.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.06, y: 0.96, z: 0.02 },
    exercises: []
  },
  {
    name: 'Superior Mesenteric Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Vein draining the small intestine and right colon.',
    function: 'Carries absorbed nutrients from the midgut to the portal vein.',
    importance: 'SMV thrombosis causes mesenteric ischemia.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.02, y: 0.92, z: 0.04 },
    exercises: []
  },
  {
    name: 'Inferior Mesenteric Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Vein draining the left colon and rectum.',
    function: 'Carries blood from the hindgut to the splenic or SMV.',
    importance: 'Drains into splenic vein or junction with SMV.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.02, y: 0.86, z: 0.02 },
    exercises: []
  },
  {
    name: 'Renal Vein (Right)',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Short vein draining the right kidney into the IVC.',
    function: 'Returns filtered blood from the right kidney to the IVC.',
    importance: 'Shorter than left renal vein.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.04, y: 0.9, z: -0.02 },
    exercises: []
  },
  {
    name: 'Renal Vein (Left)',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Longer vein draining the left kidney, crossing anterior to the aorta.',
    function: 'Returns filtered blood from the left kidney to the IVC.',
    importance: 'Receives left gonadal and left adrenal veins.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.04, y: 0.9, z: 0 },
    exercises: []
  },
  {
    name: 'Common Iliac Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Formed by union of internal and external iliac veins, joining to form IVC.',
    function: 'Drains the pelvis and lower limb.',
    importance: 'May-Thurner syndrome: left common iliac vein compressed by right common iliac artery.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.04, y: 0.76, z: 0 },
    exercises: []
  },
  {
    name: 'Femoral Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Major vein of the thigh, medial to the femoral artery.',
    function: 'Drains the thigh, becoming external iliac vein.',
    importance: 'DVT commonly occurs here. Used for femoral line placement.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.08, y: 0.58, z: 0.04 },
    exercises: []
  },
  {
    name: 'Great Saphenous Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Longest vein in the body, from medial foot to femoral vein.',
    function: 'Superficial drainage of the medial leg and thigh.',
    importance: 'Commonly used for CABG grafts. Varicose veins often involve this vein.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.06, y: 0.4, z: 0.04 },
    exercises: [
      { name: 'Calf Raises', rank: 1, description: 'Improves venous return from legs.' },
      { name: 'Walking', rank: 2, description: 'Activates calf muscle pump.' },
    ]
  },
  {
    name: 'Small Saphenous Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Superficial vein on the posterior calf, draining into popliteal vein.',
    function: 'Drains the lateral foot and posterior leg.',
    importance: 'Can be involved in varicose veins.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.1, y: 0.3, z: -0.04 },
    exercises: []
  },
  {
    name: 'Popliteal Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Deep vein behind the knee, formed by tibial veins.',
    function: 'Drains the leg, becoming the femoral vein.',
    importance: 'Common site for DVT. Ultrasound used to detect clots.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.1, y: 0.38, z: -0.03 },
    exercises: []
  },
  {
    name: 'Azygos Vein',
    type: 'vein',
    category: 'cardiovascular',
    description: 'Vein on the right side of the thoracic vertebral column.',
    function: 'Drains the posterior thoracic and abdominal walls into the SVC.',
    importance: 'Provides collateral drainage if IVC is obstructed.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.03, y: 1.1, z: -0.04 },
    exercises: []
  },
];
