export const SKULL_BONES = [
  {
    name: 'Frontal Bone',
    type: 'bone',
    category: 'skeletal',
    description: 'Forms the forehead, roof of the orbits (eye sockets), and most of the anterior cranial fossa. Contains the frontal sinuses.',
    function: 'Protects the frontal lobes of the brain, forms the superior margin of the orbits, and provides attachment for facial muscles.',
    importance: 'Critical protection for the frontal brain region. The frontal sinuses can become infected (sinusitis).',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 1.68, z: 0.08 },
    exercises: []
  },
  {
    name: 'Parietal Bone (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'One of two bones forming the superior and lateral walls of the cranium. Quadrilateral in shape with curved surfaces.',
    function: 'Protects the parietal lobes of the brain, provides attachment for temporalis muscle.',
    importance: 'Forms the majority of the cranial vault protecting the brain.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.06, y: 1.7, z: 0 },
    exercises: []
  },
  {
    name: 'Parietal Bone (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'One of two bones forming the superior and lateral walls of the cranium. Quadrilateral in shape with curved surfaces.',
    function: 'Protects the parietal lobes of the brain, provides attachment for temporalis muscle.',
    importance: 'Forms the majority of the cranial vault protecting the brain.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.06, y: 1.7, z: 0 },
    exercises: []
  },
  {
    name: 'Temporal Bone (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Complex bone forming the lateral skull base. Contains the middle and inner ear structures, including the mastoid process and styloid process.',
    function: 'Houses the organs of hearing and balance, provides attachment for muscles of mastication, protects the temporal lobe.',
    importance: 'Contains vital auditory and vestibular structures. The mastoid process can become infected (mastoiditis).',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.08, y: 1.62, z: 0 },
    exercises: []
  },
  {
    name: 'Temporal Bone (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Complex bone forming the lateral skull base. Contains the middle and inner ear structures, including the mastoid process and styloid process.',
    function: 'Houses the organs of hearing and balance, provides attachment for muscles of mastication, protects the temporal lobe.',
    importance: 'Contains vital auditory and vestibular structures. The mastoid process can become infected (mastoiditis).',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.08, y: 1.62, z: 0 },
    exercises: []
  },
  {
    name: 'Occipital Bone',
    type: 'bone',
    category: 'skeletal',
    description: 'Forms the posterior and inferior portions of the cranium. Contains the foramen magnum through which the spinal cord passes.',
    function: 'Protects the occipital lobes and cerebellum, allows passage of the spinal cord, provides attachment for neck muscles.',
    importance: 'The foramen magnum is the critical connection between brain and spinal cord.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 1.6, z: -0.1 },
    exercises: []
  },
  {
    name: 'Sphenoid Bone',
    type: 'bone',
    category: 'skeletal',
    description: 'Butterfly-shaped bone at the skull base. Articulates with all other cranial bones. Contains the sella turcica housing the pituitary gland.',
    function: 'Forms the middle cranial fossa, houses the pituitary gland, provides passage for cranial nerves and blood vessels.',
    importance: 'Central keystone bone of the skull. Houses the pituitary gland controlling many body functions.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 1.62, z: 0.02 },
    exercises: []
  },
  {
    name: 'Ethmoid Bone',
    type: 'bone',
    category: 'skeletal',
    description: 'Delicate bone between the orbits contributing to the nasal cavity and anterior cranial fossa. Contains numerous air cells.',
    function: 'Forms part of the nasal septum and lateral nasal walls, supports olfactory nerves, contributes to the medial orbital wall.',
    importance: 'Critical for sense of smell. Ethmoid sinuses commonly involved in sinusitis.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 1.64, z: 0.06 },
    exercises: []
  },
  {
    name: 'Maxilla (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'One of two bones forming the upper jaw. Contains the maxillary sinus, supports the upper teeth, and forms part of the orbit and nasal cavity.',
    function: 'Supports upper teeth, forms the hard palate, contributes to orbital floor and nasal cavity walls.',
    importance: 'Essential for chewing and facial structure. Maxillary sinus is commonly affected by infections.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.02, y: 1.58, z: 0.1 },
    exercises: []
  },
  {
    name: 'Maxilla (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'One of two bones forming the upper jaw. Contains the maxillary sinus, supports the upper teeth, and forms part of the orbit and nasal cavity.',
    function: 'Supports upper teeth, forms the hard palate, contributes to orbital floor and nasal cavity walls.',
    importance: 'Essential for chewing and facial structure. Maxillary sinus is commonly affected by infections.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.02, y: 1.58, z: 0.1 },
    exercises: []
  },
  {
    name: 'Zygomatic Bone (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'The cheekbone, forming the prominence of the cheek and part of the lateral orbital wall and floor.',
    function: 'Forms the cheek prominence, contributes to the orbit, provides attachment for muscles of mastication.',
    importance: 'Defines facial structure. Common fracture site from facial trauma.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.05, y: 1.6, z: 0.08 },
    exercises: []
  },
  {
    name: 'Zygomatic Bone (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'The cheekbone, forming the prominence of the cheek and part of the lateral orbital wall and floor.',
    function: 'Forms the cheek prominence, contributes to the orbit, provides attachment for muscles of mastication.',
    importance: 'Defines facial structure. Common fracture site from facial trauma.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.05, y: 1.6, z: 0.08 },
    exercises: []
  },
  {
    name: 'Nasal Bone (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Small rectangular bone forming the bridge of the nose together with its partner.',
    function: 'Forms the bony bridge of the nose, provides attachment for nasal cartilages.',
    importance: 'Most commonly fractured facial bone due to its prominent position.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.008, y: 1.62, z: 0.12 },
    exercises: []
  },
  {
    name: 'Nasal Bone (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Small rectangular bone forming the bridge of the nose together with its partner.',
    function: 'Forms the bony bridge of the nose, provides attachment for nasal cartilages.',
    importance: 'Most commonly fractured facial bone due to its prominent position.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.008, y: 1.62, z: 0.12 },
    exercises: []
  },
  {
    name: 'Lacrimal Bone (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Smallest facial bone, located in the medial wall of the orbit. Contains the lacrimal fossa for the tear sac.',
    function: 'Houses the lacrimal sac, forms part of the medial orbital wall.',
    importance: 'Essential for tear drainage. Blockage causes epiphora (excessive tearing).',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.02, y: 1.63, z: 0.08 },
    exercises: []
  },
  {
    name: 'Lacrimal Bone (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Smallest facial bone, located in the medial wall of the orbit. Contains the lacrimal fossa for the tear sac.',
    function: 'Houses the lacrimal sac, forms part of the medial orbital wall.',
    importance: 'Essential for tear drainage. Blockage causes epiphora (excessive tearing).',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.02, y: 1.63, z: 0.08 },
    exercises: []
  },
  {
    name: 'Palatine Bone (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'L-shaped bone forming the posterior hard palate, part of the nasal cavity floor, and part of the orbit.',
    function: 'Forms the posterior portion of the hard palate, contributes to nasal cavity and orbital walls.',
    importance: 'Essential for separation of oral and nasal cavities.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.015, y: 1.56, z: 0.02 },
    exercises: []
  },
  {
    name: 'Palatine Bone (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'L-shaped bone forming the posterior hard palate, part of the nasal cavity floor, and part of the orbit.',
    function: 'Forms the posterior portion of the hard palate, contributes to nasal cavity and orbital walls.',
    importance: 'Essential for separation of oral and nasal cavities.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.015, y: 1.56, z: 0.02 },
    exercises: []
  },
  {
    name: 'Inferior Nasal Concha (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Curved bone projecting into the nasal cavity from the lateral wall. The largest of the three nasal conchae.',
    function: 'Increases nasal surface area for warming and humidifying air, directs airflow.',
    importance: 'Essential for proper nasal function. Hypertrophy can cause nasal obstruction.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.015, y: 1.6, z: 0.08 },
    exercises: []
  },
  {
    name: 'Inferior Nasal Concha (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Curved bone projecting into the nasal cavity from the lateral wall. The largest of the three nasal conchae.',
    function: 'Increases nasal surface area for warming and humidifying air, directs airflow.',
    importance: 'Essential for proper nasal function. Hypertrophy can cause nasal obstruction.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.015, y: 1.6, z: 0.08 },
    exercises: []
  },
  {
    name: 'Vomer',
    type: 'bone',
    category: 'skeletal',
    description: 'Thin, flat bone forming the inferior and posterior portions of the nasal septum.',
    function: 'Forms the bony nasal septum separating the two nasal cavities.',
    importance: 'Deviation causes nasal obstruction and breathing difficulties.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 1.58, z: 0.06 },
    exercises: []
  },
  {
    name: 'Mandible',
    type: 'bone',
    category: 'skeletal',
    description: 'The lower jaw, the largest and strongest facial bone. The only movable bone of the skull, articulating at the temporomandibular joints.',
    function: 'Supports lower teeth, enables chewing and speech, provides attachment for muscles of mastication.',
    importance: 'Essential for eating and speaking. TMJ disorders are common and can be debilitating.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 1.52, z: 0.08 },
    exercises: [
      { name: 'Jaw Relaxation', rank: 1, description: 'Helps maintain healthy TMJ function.' },
    ]
  },
];
