export const THORAX_BONES = [
  {
    name: 'Sternum',
    type: 'bone',
    category: 'skeletal',
    description: 'Flat bone in the center of the chest composed of three parts: the manubrium (superior), body (middle), and xiphoid process (inferior). Articulates with clavicles and ribs 1-7.',
    function: 'Protects the heart and great vessels, provides attachment for ribs via costal cartilages, articulates with clavicles at sternoclavicular joints.',
    importance: 'Critical protection for the heart. Site of CPR compressions. Sternal fractures indicate significant trauma. The xiphoid process is a landmark for CPR hand placement.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0, y: 1.22, z: 0.1 },
    exercises: []
  },
  {
    name: 'Rib 1 (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'The shortest and most curved rib. Broad and flat, articulating with T1 vertebra and manubrium.',
    function: 'Protects apex of lung and subclavian vessels. Provides attachment for scalene muscles.',
    importance: 'First rib syndrome can compress brachial plexus or subclavian vessels (thoracic outlet syndrome).',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.08, y: 1.38, z: 0.06 },
    exercises: []
  },
  {
    name: 'Rib 1 (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'The shortest and most curved rib. Broad and flat, articulating with T1 vertebra and manubrium.',
    function: 'Protects apex of lung and subclavian vessels. Provides attachment for scalene muscles.',
    importance: 'First rib syndrome can compress brachial plexus or subclavian vessels (thoracic outlet syndrome).',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.08, y: 1.38, z: 0.06 },
    exercises: []
  },
  {
    name: 'Rib 2 (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Second true rib, transitional in shape between first and typical ribs. Has a rough tuberosity for serratus anterior.',
    function: 'Articulates with T1-T2, provides attachment for serratus anterior and scalene muscles.',
    importance: 'Landmark for counting ribs. Serratus anterior attachment important for scapular function.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.1, y: 1.34, z: 0.07 },
    exercises: []
  },
  {
    name: 'Rib 2 (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Second true rib, transitional in shape between first and typical ribs. Has a rough tuberosity for serratus anterior.',
    function: 'Articulates with T1-T2, provides attachment for serratus anterior and scalene muscles.',
    importance: 'Landmark for counting ribs. Serratus anterior attachment important for scapular function.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.1, y: 1.34, z: 0.07 },
    exercises: []
  },
  {
    name: 'Rib 3 (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Third true rib with typical rib morphology: head, neck, tubercle, and curved body with costal groove.',
    function: 'Protects thoracic organs, assists in breathing mechanics.',
    importance: 'Part of the thoracic cage protecting heart and lungs.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.12, y: 1.3, z: 0.08 },
    exercises: []
  },
  {
    name: 'Rib 3 (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Third true rib with typical rib morphology: head, neck, tubercle, and curved body with costal groove.',
    function: 'Protects thoracic organs, assists in breathing mechanics.',
    importance: 'Part of the thoracic cage protecting heart and lungs.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.12, y: 1.3, z: 0.08 },
    exercises: []
  },
  {
    name: 'Rib 4 (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Fourth true rib with typical morphology. Located at the level of the nipple in males.',
    function: 'Protects heart at nipple level, intercostal muscles attach along its borders.',
    importance: 'Heart is most accessible at 4th-5th intercostal space for auscultation.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.13, y: 1.25, z: 0.09 },
    exercises: []
  },
  {
    name: 'Rib 4 (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Fourth true rib with typical morphology. Located at the level of the nipple in males.',
    function: 'Protects heart at nipple level, intercostal muscles attach along its borders.',
    importance: 'Heart is most accessible at 4th-5th intercostal space for auscultation.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.13, y: 1.25, z: 0.09 },
    exercises: []
  },
  {
    name: 'Rib 5 (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Fifth true rib, typical morphology. Apex of heart located at 5th intercostal space.',
    function: 'Protects apex of heart, provides breathing mechanics support.',
    importance: 'Apex beat palpable at 5th intercostal space, midclavicular line.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.14, y: 1.2, z: 0.09 },
    exercises: []
  },
  {
    name: 'Rib 5 (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Fifth true rib, typical morphology. Apex of heart located at 5th intercostal space.',
    function: 'Protects apex of heart, provides breathing mechanics support.',
    importance: 'Apex beat palpable at 5th intercostal space, midclavicular line.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.14, y: 1.2, z: 0.09 },
    exercises: []
  },
  {
    name: 'Rib 6 (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Sixth true rib with typical morphology.',
    function: 'Protects lower heart and upper abdominal organs, assists respiration.',
    importance: 'Part of the protective thoracic cage.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.14, y: 1.15, z: 0.09 },
    exercises: []
  },
  {
    name: 'Rib 6 (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Sixth true rib with typical morphology.',
    function: 'Protects lower heart and upper abdominal organs, assists respiration.',
    importance: 'Part of the protective thoracic cage.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.14, y: 1.15, z: 0.09 },
    exercises: []
  },
  {
    name: 'Rib 7 (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Seventh and last true rib, directly attached to sternum via its own costal cartilage.',
    function: 'Forms inferior boundary of true ribs, protects upper abdominal organs.',
    importance: 'Last rib with direct sternal attachment. Common site for costochondritis.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.14, y: 1.1, z: 0.08 },
    exercises: []
  },
  {
    name: 'Rib 7 (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Seventh and last true rib, directly attached to sternum via its own costal cartilage.',
    function: 'Forms inferior boundary of true ribs, protects upper abdominal organs.',
    importance: 'Last rib with direct sternal attachment. Common site for costochondritis.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.14, y: 1.1, z: 0.08 },
    exercises: []
  },
  {
    name: 'Rib 8 (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'First false rib, attaching to sternum indirectly via cartilage of rib 7.',
    function: 'Protects upper abdominal organs (liver, stomach, spleen), assists respiration.',
    importance: 'Indirect sternal attachment provides some flexibility to thorax.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.14, y: 1.05, z: 0.07 },
    exercises: []
  },
  {
    name: 'Rib 8 (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'First false rib, attaching to sternum indirectly via cartilage of rib 7.',
    function: 'Protects upper abdominal organs (liver, stomach, spleen), assists respiration.',
    importance: 'Indirect sternal attachment provides some flexibility to thorax.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.14, y: 1.05, z: 0.07 },
    exercises: []
  },
  {
    name: 'Rib 9 (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Second false rib, cartilage attaches to cartilage of rib 8.',
    function: 'Protects kidneys and upper abdominal organs, provides thoracic expansion.',
    importance: 'Part of the costal margin protecting abdominal organs.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.13, y: 1.0, z: 0.06 },
    exercises: []
  },
  {
    name: 'Rib 9 (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Second false rib, cartilage attaches to cartilage of rib 8.',
    function: 'Protects kidneys and upper abdominal organs, provides thoracic expansion.',
    importance: 'Part of the costal margin protecting abdominal organs.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.13, y: 1.0, z: 0.06 },
    exercises: []
  },
  {
    name: 'Rib 10 (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Third false rib, may attach to rib 9 cartilage or be floating (anatomical variation).',
    function: 'Protects kidneys, provides attachment for abdominal muscles.',
    importance: 'Variable anatomy - sometimes classified as floating rib.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.12, y: 0.95, z: 0.05 },
    exercises: []
  },
  {
    name: 'Rib 10 (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Third false rib, may attach to rib 9 cartilage or be floating (anatomical variation).',
    function: 'Protects kidneys, provides attachment for abdominal muscles.',
    importance: 'Variable anatomy - sometimes classified as floating rib.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.12, y: 0.95, z: 0.05 },
    exercises: []
  },
  {
    name: 'Rib 11 (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'First floating rib with no anterior attachment. Short with no neck or tubercle.',
    function: 'Protects posterior kidneys, provides attachment for quadratus lumborum.',
    importance: 'Floating ribs more susceptible to fracture. Protects kidneys from posterior trauma.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.1, y: 0.92, z: -0.02 },
    exercises: []
  },
  {
    name: 'Rib 11 (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'First floating rib with no anterior attachment. Short with no neck or tubercle.',
    function: 'Protects posterior kidneys, provides attachment for quadratus lumborum.',
    importance: 'Floating ribs more susceptible to fracture. Protects kidneys from posterior trauma.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.1, y: 0.92, z: -0.02 },
    exercises: []
  },
  {
    name: 'Rib 12 (Left)',
    type: 'bone',
    category: 'skeletal',
    description: 'Second floating rib and shortest of all ribs. No neck, tubercle, or angle.',
    function: 'Minimal protective function, attachment for diaphragm and quadratus lumborum.',
    importance: 'Most inferior rib. Can cause pain if hypermobile.',
    modelLayer: 'skeleton_organs',
    position3D: { x: -0.08, y: 0.88, z: -0.04 },
    exercises: []
  },
  {
    name: 'Rib 12 (Right)',
    type: 'bone',
    category: 'skeletal',
    description: 'Second floating rib and shortest of all ribs. No neck, tubercle, or angle.',
    function: 'Minimal protective function, attachment for diaphragm and quadratus lumborum.',
    importance: 'Most inferior rib. Can cause pain if hypermobile.',
    modelLayer: 'skeleton_organs',
    position3D: { x: 0.08, y: 0.88, z: -0.04 },
    exercises: []
  },
];
