// HEAD AND NECK MUSCLES

export const HEAD_NECK_MUSCLES = [
  // ==================== FACIAL EXPRESSION MUSCLES ====================
  {
    name: 'Frontalis',
    type: 'muscle',
    category: 'upper_body',
    description: 'Thin muscle covering the forehead, part of the occipitofrontalis. Has no bony attachments anteriorly.',
    function: 'Raises the eyebrows, wrinkles the forehead horizontally, expresses surprise or concern.',
    importance: 'Primary muscle of forehead expression. Weakness causes brow ptosis.',
    movement: 'Contraction pulls the scalp forward, raising the eyebrows.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0, y: 1.72, z: 0.1 },
    exercises: []
  },
  {
    name: 'Orbicularis Oculi',
    type: 'muscle',
    category: 'upper_body',
    description: 'Sphincter muscle surrounding the eye, with orbital, palpebral, and lacrimal parts.',
    function: 'Closes the eyelids, protects the eye, assists in tear drainage, creates crow\'s feet wrinkles.',
    importance: 'Essential for blinking and eye protection. Paralysis causes dry eye.',
    movement: 'Contraction closes the eye gently (palpebral) or forcefully (orbital).',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.03, y: 1.64, z: 0.1 },
    exercises: []
  },
  {
    name: 'Orbicularis Oris',
    type: 'muscle',
    category: 'upper_body',
    description: 'Complex sphincter muscle of the lips, formed by multiple facial muscles converging.',
    function: 'Closes and purses the lips, essential for speech, eating, kissing, and whistling.',
    importance: 'Critical for speech articulation and oral competence.',
    movement: 'Contraction closes and purses the lips.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0, y: 1.56, z: 0.12 },
    exercises: []
  },
  {
    name: 'Zygomaticus Major',
    type: 'muscle',
    category: 'upper_body',
    description: 'Muscle extending from zygomatic bone to the corner of the mouth.',
    function: 'Draws the corner of the mouth upward and laterally, creating a smile.',
    importance: 'Primary muscle of smiling. Paralysis causes facial droop.',
    movement: 'Contraction pulls the mouth corner up and back for smiling.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.04, y: 1.58, z: 0.1 },
    exercises: []
  },
  {
    name: 'Zygomaticus Minor',
    type: 'muscle',
    category: 'upper_body',
    description: 'Smaller muscle medial to zygomaticus major, from zygomatic bone to upper lip.',
    function: 'Elevates the upper lip, assists in smiling and showing upper teeth.',
    importance: 'Contributes to facial expression complexity.',
    movement: 'Contraction elevates the upper lip.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.03, y: 1.59, z: 0.1 },
    exercises: []
  },
  {
    name: 'Levator Labii Superioris',
    type: 'muscle',
    category: 'upper_body',
    description: 'Muscle from the infraorbital margin to the upper lip.',
    function: 'Elevates the upper lip, shows upper teeth, expresses disgust.',
    importance: 'Part of sneering expression and upper lip movement.',
    movement: 'Contraction raises the upper lip.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.025, y: 1.6, z: 0.11 },
    exercises: []
  },
  {
    name: 'Depressor Anguli Oris',
    type: 'muscle',
    category: 'upper_body',
    description: 'Triangular muscle from mandible to the corner of the mouth.',
    function: 'Depresses the corner of the mouth, creates frowning expression.',
    importance: 'Primary muscle for sad or disapproving expressions.',
    movement: 'Contraction pulls mouth corner down for frown.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.03, y: 1.54, z: 0.1 },
    exercises: []
  },
  {
    name: 'Mentalis',
    type: 'muscle',
    category: 'upper_body',
    description: 'Muscle of the chin, originates from mandible and inserts into chin skin.',
    function: 'Elevates and protrudes the lower lip, wrinkles the chin, expresses doubt.',
    importance: 'Creates the pouting expression and chin dimpling.',
    movement: 'Contraction pushes the lower lip up and out.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0, y: 1.52, z: 0.1 },
    exercises: []
  },
  {
    name: 'Buccinator',
    type: 'muscle',
    category: 'upper_body',
    description: 'Deep muscle of the cheek, forming the lateral wall of the oral cavity.',
    function: 'Compresses the cheek against teeth, aids in chewing and blowing, prevents food accumulation.',
    importance: 'Essential for chewing, blowing instruments, and sucking.',
    movement: 'Contraction presses cheek against teeth.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.05, y: 1.56, z: 0.06 },
    exercises: []
  },
  {
    name: 'Platysma',
    type: 'muscle',
    category: 'upper_body',
    description: 'Thin, broad muscle covering the anterior neck from chest to mandible.',
    function: 'Depresses the mandible and lower lip, tenses neck skin, expresses horror or fright.',
    importance: 'Creates tense neck appearance in extreme expressions.',
    movement: 'Contraction tenses the neck skin and depresses the jaw.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.05, y: 1.45, z: 0.06 },
    exercises: []
  },
  {
    name: 'Corrugator Supercilii',
    type: 'muscle',
    category: 'upper_body',
    description: 'Small muscle at the medial end of the eyebrow.',
    function: 'Draws the eyebrow downward and medially, creates vertical wrinkles between brows.',
    importance: 'Primary frowning muscle. Target of Botox for frown lines.',
    movement: 'Contraction brings eyebrows together for frowning.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.015, y: 1.66, z: 0.1 },
    exercises: []
  },
  {
    name: 'Procerus',
    type: 'muscle',
    category: 'upper_body',
    description: 'Small muscle at the bridge of the nose.',
    function: 'Pulls the medial brow downward, creates horizontal wrinkles over the nose bridge.',
    importance: 'Contributes to frowning and disgust expressions.',
    movement: 'Contraction wrinkles the nose bridge.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0, y: 1.64, z: 0.12 },
    exercises: []
  },
  {
    name: 'Nasalis',
    type: 'muscle',
    category: 'upper_body',
    description: 'Muscle covering the nose with transverse and alar parts.',
    function: 'Compresses the nasal aperture (transverse) or flares the nostrils (alar).',
    importance: 'Assists in deep breathing by flaring nostrils.',
    movement: 'Contraction compresses or dilates the nostrils.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.01, y: 1.6, z: 0.13 },
    exercises: []
  },
  {
    name: 'Risorius',
    type: 'muscle',
    category: 'upper_body',
    description: 'Thin muscle from the fascia over masseter to the corner of the mouth.',
    function: 'Retracts the angle of the mouth laterally, produces an insincere or nervous smile.',
    importance: 'Creates the grimacing expression.',
    movement: 'Contraction pulls mouth corner backward.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.05, y: 1.56, z: 0.08 },
    exercises: []
  },

  // ==================== MASTICATION MUSCLES ====================
  {
    name: 'Masseter',
    type: 'muscle',
    category: 'upper_body',
    description: 'Powerful quadrilateral muscle from zygomatic arch to mandible. One of the strongest muscles.',
    function: 'Primary elevator of the mandible for chewing, produces powerful bite force.',
    importance: 'Essential for chewing. Hypertrophy causes squared jaw. TMJ disorders affect it.',
    movement: 'Contraction closes the jaw with great force.',
    recoveryTime: 36,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.06, y: 1.56, z: 0.04 },
    exercises: [
      { name: 'Jaw Exercises', rank: 1, description: 'Strengthens masseter for TMJ health.' },
    ]
  },
  {
    name: 'Temporalis',
    type: 'muscle',
    category: 'upper_body',
    description: 'Fan-shaped muscle covering the temporal fossa, converging to insert on the coronoid process.',
    function: 'Elevates and retracts the mandible, assists in side-to-side grinding motion.',
    importance: 'Major chewing muscle. Tension causes temporal headaches.',
    movement: 'Contraction elevates the jaw and pulls it backward.',
    recoveryTime: 36,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.06, y: 1.64, z: 0.02 },
    exercises: []
  },
  {
    name: 'Lateral Pterygoid',
    type: 'muscle',
    category: 'upper_body',
    description: 'Two-headed muscle deep in the infratemporal fossa, runs horizontally.',
    function: 'Opens the jaw (depresses), protrudes the mandible, assists in side-to-side movement.',
    importance: 'Only muscle that opens the jaw against resistance. Key in TMJ function.',
    movement: 'Contraction protrudes and opens the jaw.',
    recoveryTime: 36,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.05, y: 1.58, z: 0 },
    exercises: []
  },
  {
    name: 'Medial Pterygoid',
    type: 'muscle',
    category: 'upper_body',
    description: 'Deep muscle medial to the mandible, mirror image of masseter.',
    function: 'Elevates the mandible, assists in side-to-side grinding for chewing.',
    importance: 'Works with masseter as mandibular sling. Involved in teeth grinding (bruxism).',
    movement: 'Contraction elevates and protrudes the jaw.',
    recoveryTime: 36,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.04, y: 1.56, z: 0.01 },
    exercises: []
  },

  // ==================== NECK MUSCLES - ANTERIOR ====================
  {
    name: 'Sternocleidomastoid',
    type: 'muscle',
    category: 'upper_body',
    description: 'Prominent strap-like muscle from sternum and clavicle to mastoid process. Creates V-shape in neck.',
    function: 'Unilateral: rotates head to opposite side, lateral flexion. Bilateral: flexes the neck, extends the head.',
    importance: 'Key neck landmark. Torticollis involves spasm of this muscle.',
    movement: 'Contraction turns head to opposite side and tilts to same side.',
    recoveryTime: 36,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.06, y: 1.45, z: 0.03 },
    exercises: [
      { name: 'Neck Rotation', rank: 1, description: 'Strengthens SCM for neck stability.' },
      { name: 'Neck Flexion', rank: 2, description: 'Targets SCM for forward head posture.' },
    ]
  },
  {
    name: 'Scalene Anterior',
    type: 'muscle',
    category: 'upper_body',
    description: 'Lateral neck muscle from cervical vertebrae to first rib. Part of the scalene group.',
    function: 'Elevates the first rib (inspiration), lateral flexion and rotation of the neck.',
    importance: 'Accessory breathing muscle. Involved in thoracic outlet syndrome.',
    movement: 'Contraction elevates the first rib and bends the neck.',
    recoveryTime: 36,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.04, y: 1.46, z: 0.01 },
    exercises: []
  },
  {
    name: 'Scalene Medius',
    type: 'muscle',
    category: 'upper_body',
    description: 'Largest of the scalene muscles, from cervical vertebrae to first rib.',
    function: 'Elevates the first rib, lateral flexion of the neck.',
    importance: 'Brachial plexus passes between anterior and middle scalenes.',
    movement: 'Contraction elevates first rib and tilts neck.',
    recoveryTime: 36,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.05, y: 1.46, z: 0 },
    exercises: []
  },
  {
    name: 'Scalene Posterior',
    type: 'muscle',
    category: 'upper_body',
    description: 'Smallest scalene, from cervical vertebrae to second rib.',
    function: 'Elevates the second rib, lateral flexion of the neck.',
    importance: 'Accessory breathing muscle.',
    movement: 'Contraction elevates second rib.',
    recoveryTime: 36,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.06, y: 1.46, z: -0.01 },
    exercises: []
  },
  {
    name: 'Longus Colli',
    type: 'muscle',
    category: 'core',
    description: 'Deep neck flexor along the anterior cervical spine from atlas to T3.',
    function: 'Flexes the cervical spine, rotates and laterally flexes the neck.',
    importance: 'Key deep neck flexor for cervical stability. Weakness linked to neck pain.',
    movement: 'Contraction flexes the neck forward.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.02, y: 1.48, z: 0.02 },
    exercises: [
      { name: 'Chin Tucks', rank: 1, description: 'Activates deep neck flexors.' },
    ]
  },
  {
    name: 'Longus Capitis',
    type: 'muscle',
    category: 'core',
    description: 'Deep neck muscle from cervical vertebrae to the base of the skull.',
    function: 'Flexes the head on the neck, slight rotation.',
    importance: 'Works with longus colli for deep neck flexion.',
    movement: 'Contraction nods the head forward.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.015, y: 1.52, z: 0.02 },
    exercises: []
  },

  // ==================== SUPRAHYOID AND INFRAHYOID MUSCLES ====================
  {
    name: 'Digastric',
    type: 'muscle',
    category: 'upper_body',
    description: 'Two-bellied muscle (anterior and posterior) connected by intermediate tendon at hyoid.',
    function: 'Depresses the mandible (opens mouth), elevates the hyoid during swallowing.',
    importance: 'Key muscle for opening the mouth and swallowing.',
    movement: 'Contraction opens the mouth or raises the hyoid.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.03, y: 1.5, z: 0.04 },
    exercises: []
  },
  {
    name: 'Mylohyoid',
    type: 'muscle',
    category: 'upper_body',
    description: 'Flat muscle forming the floor of the mouth from mandible to hyoid.',
    function: 'Elevates the floor of mouth and tongue, elevates hyoid for swallowing.',
    importance: 'Forms the muscular floor of the mouth. Essential for swallowing.',
    movement: 'Contraction elevates the tongue and hyoid.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0, y: 1.5, z: 0.05 },
    exercises: []
  },
  {
    name: 'Geniohyoid',
    type: 'muscle',
    category: 'upper_body',
    description: 'Narrow muscle from mental spine of mandible to hyoid, above mylohyoid.',
    function: 'Pulls the hyoid forward and upward, assists in opening mouth.',
    importance: 'Assists in swallowing and opening the mouth.',
    movement: 'Contraction pulls hyoid forward.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0, y: 1.49, z: 0.04 },
    exercises: []
  },
  {
    name: 'Stylohyoid',
    type: 'muscle',
    category: 'upper_body',
    description: 'Slender muscle from styloid process to hyoid bone.',
    function: 'Elevates and retracts the hyoid during swallowing.',
    importance: 'Part of the swallowing mechanism.',
    movement: 'Contraction pulls hyoid up and back.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.04, y: 1.52, z: 0.02 },
    exercises: []
  },
  {
    name: 'Sternohyoid',
    type: 'muscle',
    category: 'upper_body',
    description: 'Thin strap muscle from sternum to hyoid bone.',
    function: 'Depresses the hyoid after swallowing.',
    importance: 'Returns hyoid to resting position after swallowing.',
    movement: 'Contraction pulls hyoid down.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.01, y: 1.44, z: 0.06 },
    exercises: []
  },
  {
    name: 'Omohyoid',
    type: 'muscle',
    category: 'upper_body',
    description: 'Two-bellied muscle from scapula to hyoid with intermediate tendon.',
    function: 'Depresses and retracts the hyoid bone.',
    importance: 'Helps stabilize the hyoid. Landmark for neck surgery.',
    movement: 'Contraction pulls hyoid down and back.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.04, y: 1.42, z: 0.04 },
    exercises: []
  },
  {
    name: 'Sternothyroid',
    type: 'muscle',
    category: 'upper_body',
    description: 'Strap muscle from sternum to thyroid cartilage.',
    function: 'Depresses the larynx after swallowing or vocalization.',
    importance: 'Part of laryngeal depression mechanism.',
    movement: 'Contraction pulls larynx down.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.015, y: 1.42, z: 0.05 },
    exercises: []
  },
  {
    name: 'Thyrohyoid',
    type: 'muscle',
    category: 'upper_body',
    description: 'Short muscle from thyroid cartilage to hyoid bone.',
    function: 'Depresses the hyoid or elevates the larynx depending on fixation.',
    importance: 'Important for pitch change during speaking.',
    movement: 'Contraction brings hyoid and larynx together.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.01, y: 1.46, z: 0.05 },
    exercises: []
  },

  // ==================== POSTERIOR NECK MUSCLES ====================
  {
    name: 'Splenius Capitis',
    type: 'muscle',
    category: 'upper_body',
    description: 'Broad strap-like muscle from lower cervical/upper thoracic spinous processes to mastoid and occiput.',
    function: 'Extends the head and neck, rotates the head to the same side, lateral flexion.',
    importance: 'Major neck extensor. Tension causes cervicogenic headaches.',
    movement: 'Bilateral contraction extends the head, unilateral rotates to same side.',
    recoveryTime: 36,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.04, y: 1.52, z: -0.06 },
    exercises: [
      { name: 'Neck Extension', rank: 1, description: 'Strengthens posterior neck muscles.' },
    ]
  },
  {
    name: 'Splenius Cervicis',
    type: 'muscle',
    category: 'upper_body',
    description: 'Lies deep to splenius capitis, from upper thoracic to upper cervical transverse processes.',
    function: 'Extends and rotates the cervical spine.',
    importance: 'Assists in cervical extension and rotation.',
    movement: 'Contraction extends and rotates the neck.',
    recoveryTime: 36,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.03, y: 1.48, z: -0.06 },
    exercises: []
  },
  {
    name: 'Semispinalis Capitis',
    type: 'muscle',
    category: 'upper_body',
    description: 'Deep neck muscle from thoracic and cervical vertebrae to the occiput.',
    function: 'Extends and rotates the head, important postural muscle.',
    importance: 'Major head extensor. Trigger points cause posterior headaches.',
    movement: 'Contraction extends the head and rotates slightly.',
    recoveryTime: 36,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.02, y: 1.56, z: -0.08 },
    exercises: []
  },
  {
    name: 'Rectus Capitis Posterior Major',
    type: 'muscle',
    category: 'upper_body',
    description: 'Suboccipital muscle from C2 spinous process to inferior nuchal line.',
    function: 'Extends and rotates the head at the atlantoaxial joint.',
    importance: 'Part of suboccipital group causing tension headaches.',
    movement: 'Contraction extends and rotates the head.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.02, y: 1.58, z: -0.1 },
    exercises: []
  },
  {
    name: 'Rectus Capitis Posterior Minor',
    type: 'muscle',
    category: 'upper_body',
    description: 'Small suboccipital muscle from C1 posterior tubercle to inferior nuchal line.',
    function: 'Extends the head at the atlanto-occipital joint.',
    importance: 'Connected to dura mater, may contribute to cervicogenic headaches.',
    movement: 'Contraction extends the head.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.01, y: 1.58, z: -0.1 },
    exercises: []
  },
  {
    name: 'Obliquus Capitis Superior',
    type: 'muscle',
    category: 'upper_body',
    description: 'Suboccipital muscle from C1 transverse process to occiput.',
    function: 'Extends and laterally flexes the head.',
    importance: 'Fine control of head movement at the atlantoaxial joint.',
    movement: 'Contraction tilts and extends the head.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.025, y: 1.58, z: -0.09 },
    exercises: []
  },
  {
    name: 'Obliquus Capitis Inferior',
    type: 'muscle',
    category: 'upper_body',
    description: 'Suboccipital muscle from C2 spinous process to C1 transverse process.',
    function: 'Rotates the atlas on the axis, turning the head to the same side.',
    importance: 'Primary rotator at C1-C2 joint.',
    movement: 'Contraction rotates C1 on C2.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.03, y: 1.56, z: -0.1 },
    exercises: []
  },

  // ==================== TONGUE MUSCLES ====================
  {
    name: 'Genioglossus',
    type: 'muscle',
    category: 'upper_body',
    description: 'Fan-shaped muscle forming the bulk of the tongue, from mental spine to tongue body.',
    function: 'Protrudes the tongue, depresses the center creating a trough.',
    importance: 'Main tongue protruder. Weakness causes speech difficulties.',
    movement: 'Contraction sticks out the tongue.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0, y: 1.54, z: 0.06 },
    exercises: []
  },
  {
    name: 'Hyoglossus',
    type: 'muscle',
    category: 'upper_body',
    description: 'Thin quadrilateral muscle from hyoid to side of tongue.',
    function: 'Depresses and retracts the tongue.',
    importance: 'Flattens the tongue during swallowing.',
    movement: 'Contraction pulls tongue down and back.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.02, y: 1.52, z: 0.05 },
    exercises: []
  },
  {
    name: 'Styloglossus',
    type: 'muscle',
    category: 'upper_body',
    description: 'Muscle from styloid process to lateral tongue.',
    function: 'Retracts and elevates the tongue.',
    importance: 'Draws tongue up and back during swallowing.',
    movement: 'Contraction pulls tongue up and back.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.03, y: 1.54, z: 0.04 },
    exercises: []
  },
  {
    name: 'Palatoglossus',
    type: 'muscle',
    category: 'upper_body',
    description: 'Muscle within the palatoglossal arch from soft palate to tongue.',
    function: 'Elevates the posterior tongue, depresses the soft palate.',
    importance: 'Closes off the oral cavity from the pharynx.',
    movement: 'Contraction narrows the oropharyngeal isthmus.',
    recoveryTime: 24,
    modelLayer: 'muscles_bones',
    position3D: { x: 0.02, y: 1.56, z: 0.03 },
    exercises: []
  },
];
